"""add weather_requests

Revision ID: 8f743495a9a3
Revises: 4d61fe377bca
Create Date: 2025-10-18 21:13:57.397729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f743495a9a3'
down_revision: Union[str, Sequence[str], None] = '4d61fe377bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requested_at_utc', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('query_city', sa.String(), nullable=True),
    sa.Column('query_lat', sa.Float(), nullable=True),
    sa.Column('query_lon', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('result_temp_c', sa.Float(), nullable=True),
    sa.Column('observed_at_utc', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result_raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_requests')
    # ### end Alembic commands ###
