"""create agent_requests table

Revision ID: be392f16549e
Revises: 8f743495a9a3
Create Date: 2025-10-19 17:25:53.135319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be392f16549e'
down_revision: Union[str, Sequence[str], None] = '8f743495a9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requested_at_utc', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('agent_response', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_detail', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_requests')
    # ### end Alembic commands ###
